baseURL: "https://phy.github.io" 
title: Pranaya Pratik Das
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 2
        - name: Papers
          url: papers/
          weight: 1
	-name: Newsletter
	url: newsletter/
	weight: 3
      #  - name: Courses
      #   url: courses/
      #  weight: 3

params:
    description: "I am a Senior Research Fellow in the Department of Physics and Astronomy at NIT Rourkela and I am about to complete my PhD in Theoretical Physics. My research focuses on Quantum Chaos. "
    author: Pranaya Pratik Das
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","papers","newsletter"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pranaya Pratik Das
          subtitle: "I am a Senior Research Fellow in the Department of Physics and Astronomy at NIT Rourkela and I am about to complete my PhD in Theoretical Physics. My work explores the intricate signatures of chaos in both classical and quantum systems, spanning diverse domains such as black hole thermodynamics, billiard systems with mixed curvature, and time-dependent quantum correlations. With a keen interest in emergent behavior and collective dynamics, I also investigates pattern formation in active media and the role of symmetry in nonlinear oscillators. I bring a multidisciplinary approach to complex systems, aiming to deepen our understanding of how chaos manifests across physical scales and geometries."
          imageUrl: "pp.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Books
              url: books/
	    -name: Newsletter
	      url: newsletter/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: PPD_CV.pdf
        - name: Email
          url: mailto:pranaya.phy@outlook.com
        - name: Instagram
          url: https://www.instagram.com/pranaya.pratik.das
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=lutErqEAAAAJ&hl=en
        - name: Researchgate
          url: https://www.researchgate.net/profile/Pranaya-DasS

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Pranaya Pratik Das"
      icon: favicon.ico
      iconHeight: 22

language:
	en:
		languageName: "English"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: dracula 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 1
