baseURL: "https://phy.github.io" 
title: Pranaya Pratik Das
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 2
        - name: Papers
          url: papers/
          weight: 1
#	- name: News
#	  url: data/
#	  weight: 3

params:
    description: "I am a Senior Research Fellow in the Department of Physics and Astronomy at NIT Rourkela and I am about to complete my PhD in Theoretical Physics. My research focuses on Quantum Chaos. "
    author: Pranaya Pratik Das
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pranaya Pratik Das
          subtitle: "I am a **Senior Research Fellow** in the Department of Physics and Astronomy at <u><a href='https://www.nitrkl.ac.in/PH' target='_blank'> NIT Rourkela</a> </u>and I am about to complete my PhD in Theoretical Physics. My work explores the intricate signatures of chaos in both classical and quantum systems, spanning diverse domains such as black hole thermodynamics, billiard systems with mixed curvature, and time-dependent quantum correlations. With a keen interest in emergent behavior and collective dynamics, I also investigates pattern formation in active media and the role of symmetry in nonlinear oscillators. I bring a multidisciplinary approach to complex systems, aiming to deepen our understanding of how chaos manifests across physical scales and geometries."
          imageUrl: "pp.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Books
              url: books/
#	    - name: News
#	      url: news/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: PPD_CV.pdf
        - name: Email
          url: mailto:pranaya.phy@outlook.com
        - name: Instagram
          url: https://www.instagram.com/pranaya.pratik.das
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=lutErqEAAAAJ&hl=en
        - name: Researchgate
          url: https://www.researchgate.net/profile/Pranaya-Das
        - name: ORCID
          url: https://orcid.org/0000-0002-6025-7719

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Pranaya Pratik Das"
      icon: favicon.ico
      iconHeight: 22

markup:
  blackFriday:
    angledQuotes: false
    extensions: null
    extensionsMask: null
    footnoteAnchorPrefix: ""
    footnoteReturnLinkContents: ""
    fractions: true
    hrefTargetBlank: false
    latexDashes: true
    nofollowLinks: false
    noreferrerLinks: false
    plainIDAnchors: true
    skipHTML: false
    smartDashes: true
    smartypants: true
    smartypantsQuotesNBSP: false
    taskLists: true
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: autumn
    tabWidth: 4
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2

